FROM python:3.10-slim-buster

WORKDIR ${HOME}/test

COPY requirements.txt requirements.txt
COPY api/ ./api

RUN pip install -r requirements.txt && \
    pip install pytest flake8 pytest-cov && \
    python -m flake8 && \
    python -m pytest --cov=api/src
